### ISSUE TITLE
Cannot construct instance of LanguagePermission in getProjectMember

### ISSUE THREAD

**Issue by hiqua** [crowdin/crowdin-api-client-java#53]
While using this snippet:
```kotlin
    @Test
    fun testCrash() {
        val baseUrl = "https://translate.loophabits.org"
        val t = "YOUR_OWN_TOKEN"
        val organization = "loop-habit-tracker-api-test"
        val credentials = Credentials(t, organization, baseUrl)
        val client = Client(credentials)
        client.usersApi.getProjectMember(440668L, 14614530L)
    }
```

I get the following error:

```
HttpException(error=HttpException.Error(code=null, message=Cannot construct instance of `com.crowdin.client.users.model.LanguagePermission` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('translator')
 at [Source: (String)"{"data":{"id":14614530,"username":"hiq2","fullName":"Quentin","role":"translator","permissions":{"tw":"translator","ar-BH":"translator","lg":"translator"},"avatarUrl":"https:\/\/crowdin-static.downloads.crowdin.com\/avatar\/14614530\/medium\/bb2591b51932e79e834e744523e847ba.png","joinedAt":"2021-02-08T09:27:24+00:00","timezone":"Europe\/Zurich"}}"; line: 1, column: 103] (through reference chain: com.crowdin.client.users.model.ProjectMemberResponseObject["data"]->com.crowdin.client.users.model.ProjectMember["permissions"]->java.util.LinkedHashMap["tw"])))
	at com.crowdin.client.core.http.exceptions.HttpException.fromMessage(HttpException.java:22)
	at com.crowdin.client.core.http.impl.http.ApacheHttpClient.request(ApacheHttpClient.java:132)
	at com.crowdin.client.core.http.impl.http.ApacheHttpClient.get(ApacheHttpClient.java:76)
	at com.crowdin.client.users.UsersApi.getProjectMember(UsersApi.java:52)
```

I'm interested in these permissions: I want to get the list of project members and which languages they translated, so that I can give them proper credit.

I'm using the latest version of the API client library (1.3.3).

**Comment by frombetelgeuse** [comment]
Hi, @hiqua !

Instead of `client.usersApi.getProjectMember`, you should use `client.usersApi.getMemberInfo`. With the new update, this method returns fields that you need.

**Comment by hiqua** [comment]
Thanks a lot @frombetelgeuse, it seems to be working!
