### ISSUE TITLE
Get 403 (Forbidden) while calling `com.crowdin.client.teams.TeamsApi.listTeams(TeamsApi.java:56)`

### ISSUE THREAD

**Issue by kptfh** [crowdin/crowdin-api-client-java#88]
HttpException(error=HttpException.Error(code=403, message=Forbidden))
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:119)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDefault(StdValueInstantiator.java:270)
	at com.fasterxml.jackson.databind.deser.std.ThrowableDeserializer.deserializeFromObject(ThrowableDeserializer.java:149)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:164)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3436)
	at com.crowdin.client.core.http.impl.json.CrowdinApiExceptionDeserializer.deserialize(CrowdinApiExceptionDeserializer.java:35)
	at com.crowdin.client.core.http.impl.json.CrowdinApiExceptionDeserializer.deserialize(CrowdinApiExceptionDeserializer.java:17)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4526)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3468)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3436)
	at com.crowdin.client.core.http.impl.json.JacksonJsonTransformer.parse(JacksonJsonTransformer.java:60)
	at com.playtika.services.infra.translation.service.crowdin.http.ApacheHttpClient.request(ApacheHttpClient.java:91)
	at com.playtika.services.infra.translation.service.crowdin.http.ApacheHttpClient.get(ApacheHttpClient.java:53)
	at com.crowdin.client.teams.TeamsApi.listTeams(TeamsApi.java:56)

**Comment by kptfh** [comment]
Oh I see it in Enterprise API 
https://developer.crowdin.com/enterprise/api/v2/

**Comment by kptfh** [comment]
But still has an error even when run it via Postman

**Comment by OlenkaCrowdin** [comment]
Hi @kptfh! 

Access is forbidden because it is necessary to have admin rights in the organization.

If you want to use this method, please ask other admins to grant you the same role in the organization: 

![admin_access](https://user-images.githubusercontent.com/73114986/174825422-3d43b2cb-3cd2-4a86-bdfa-0123b9261731.png)

Hope it has shed light on the matter!
